### ISSUE TITLE
Doesnt work if background-image and size set in style tag, instead of inline style = "background-image: url();"

### ISSUE THREAD

**Issue by michaelDotco2** [Metafalica/background-size-emu#3]
Firstly this script doesnt work.
Secondly it causes a "sotp running this script?" popup .

**Comment by Metafalica** [comment]
Give me more info about the error. Lice code line and etc.
Did you tested the demo pages? Do they work for you?

**Comment by michaelDotco2** [comment]
I don't know if it is working or not, cant really tell with your page setup.

There is no line number just a popup.

The script does absolutely nothing.

**Comment by Metafalica** [comment]
How you can don't know this? Does the image in first page scales when you resize the browser?
For me it work fine even in ie6.

Provide me a simplest html page code that causes script to not work.

**Comment by michaelDotco2** [comment]
Yes it does.



<div id="banner-map-225" class=" col-xxs-12 col-xs-12 col-sm-4 col-md-3 col-lg-3 tile">
	<div class="banner-map">
		<div class="visible-xxs"><div id="pl_66003587637" data-line-height="1.2" class=" text-label ui- ui--handle" style="left: 2.72109%; top: 10%; position: absolute;"><p style="line-height: 1.2;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231" style="line-height: 1.2;"><span style="color:#000000">Choose a chair<br>
							pick a paint<br>
							make it yours</span></a></p>
			</div><div id="pl_121734803257" data-line-height="1.05" class=" text-label ui- ui--handle" style="left: 2.38095%; top: 71px; padding: 0px; position: absolute;"><h3 style="line-height: 1.05;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231"><span style="color:#000000">SITTING</span><br>
						<span style="color:#cc0000">PRETTY<br>
							&gt;</span></a></h3>
			</div></div>
		<div class="visible-xs"><div id="pl_950425264430" data-line-height="1.05" class=" text-label ui- active ui--handle" style="left: 9.9833px; top: 66px; padding: 0px; position: absolute;"><h3 style="line-height: 1.05;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231"><span style="color:#000000">SITTING</span><br>
						<span style="color:#cc0000">PRETTY<br>
							&gt;</span></a></h3>
			</div><div id="pl_145247459719" data-line-height="1.2" class=" text-label ui- active ui--handle" style="left: 12px; top: 15.9833px; position: absolute;"><p style="line-height: 1.2;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231" style="line-height: 1.2;"><span style="color:#000000">Choose a chair<br>
							pick a paint<br>
							make it yours</span></a></p>
			</div></div>
		<div class="visible-sm"><div id="pl_158235766636" data-line-height="1.05" class=" text-label ui- ui--handle" style="left: 16px; top: 70px; padding: 0px; position: absolute;"><h3 style="line-height: 1.05;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231"><span style="color:#000000">SITTING</span><br>
						<span style="color:#cc0000">PRETTY<br>
							&gt;</span></a></h3>
			</div><div id="pl_948068105122" data-line-height="1.2" class=" text-label ui- ui--handle" style="left: 20px; top: 16.9833px; position: absolute;"><p style="line-height: 1.2;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231" style="line-height: 1.2;"><span style="color:#000000">Choose a chair<br>
							pick a paint<br>
							make it yours</span></a></p>
			</div></div>
		<div class="visible-md"><div id="pl_302801261358" data-line-height="1.15" class=" text-label ui- ui--handle" style="left: 14.6333px; top: 28.125%; padding: 0px; position: absolute;"><h3 style="line-height: 1.15;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231"><span style="color:#000000">SITTING</span><br>
						<span style="color:#cc0000">PRETTY<br>
							&gt;</span></a></h3>
			</div><div id="pl_246261148012" data-line-height="1.2" class=" text-label ui- ui--handle" style="left: 14.9667px; top: 8.33333%; position: absolute;"><p style="line-height: 1.2;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231" style="line-height: 1.2;"><span style="color:#000000">Choose a chair<br>
							pick a paint<br>
							make it yours</span></a></p>
			</div></div>
		<div class="visible-lg"><div id="pl_172358059015" data-line-height="1.1" class=" text-label ui- ui--handle" style="left: 5.37975%; top: 30.2083%; padding: 0px; position: absolute;"><h3 style="line-height: 1.1;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231"><span style="color:#000000">SITTING</span><br>
						<span style="color:#cc0000">PRETTY<br>
							&gt;</span></a></h3>
			</div><div id="pl_419915694895" data-line-height="1.2" class=" text-label ui- ui--handle" style="left: 6.32911%; top: 32px; position: absolute;"><p style="line-height: 1.2;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231" style="line-height: 1.2;"><span style="color:#000000">Choose a chair<br>
							pick a paint<br>
							make it yours</span></a></p>
			</div></div>
	</div>
</div>
<style>
							#banner-map-225 .banner-map {
			height: 288px;
			background-image: url(shared-assets/images/banner-maps/banner_group_225_orig.jpg);
			background-position: 98% 0%;
			background-repeat: no-repeat;
			position: relative;

							background-size: 516px auto;
						}
				@media (max-width: 1366px) {
		#banner-map-225 .banner-map {
			height: 288px;
			background-position: 98% 0%;
			background-repeat: no-repeat;
							background-size: 516px auto;
						}
	}
						@media (max-width: 1365px) {
		#banner-map-225 .banner-map {
			height: 288px;
			background-position: 80% 1%;
			background-repeat: no-repeat;
							background-size: 402px auto;
						}
	}
						@media (max-width: 1023px) {
		#banner-map-225 .banner-map {
			height: 233px;
			background-position: 50% 0%;
			background-repeat: no-repeat;
							background-size: cover;
						}
	}
						@media (max-width: 767px) {
		#banner-map-225 .banner-map {
			height: 180px;
			background-position: 97% 2%;
			background-repeat: no-repeat;
							background-size: 1025px auto;
						}
	}
						@media (max-width: 479px) {
		#banner-map-225 .banner-map {
			height: 160px;
			background-position: 97% 3%;
			background-repeat: no-repeat;
							background-size: 533px auto;
						}
	}
</style>

**Comment by Metafalica** [comment]
The way you gave me the code is terrible. Please, archive it and upload somewhere, so I can test it.

**Comment by michaelDotco2** [comment]
updated - Github was formatting

**Comment by Metafalica** [comment]
Would be much faster for me to find solution if you gave me full html page code. This is is partial.
But I trying to restore this one and see.

**Comment by Metafalica** [comment]
I restored it into this:
[code]<html>
	<head>
		<title>test bg sz emu</title>
			
				<style>
									#banner-map-225 .banner-map {
					height: 288px;
					background-image: url(shared-assets/images/banner-maps/banner_group_225_orig.jpg);
					background-position: 98% 0%;
					background-repeat: no-repeat;
					position: relative;

									background-size: 516px auto;
								}
						@media (max-width: 1366px) {
				#banner-map-225 .banner-map {
					height: 288px;
					background-position: 98% 0%;
					background-repeat: no-repeat;
									background-size: 516px auto;
								}
			}
								@media (max-width: 1365px) {
				#banner-map-225 .banner-map {
					height: 288px;
					background-position: 80% 1%;
					background-repeat: no-repeat;
									background-size: 402px auto;
								}
			}
								@media (max-width: 1023px) {
				#banner-map-225 .banner-map {
					height: 233px;
					background-position: 50% 0%;
					background-repeat: no-repeat;
									background-size: cover;
								}
			}
								@media (max-width: 767px) {
				#banner-map-225 .banner-map {
					height: 180px;
					background-position: 97% 2%;
					background-repeat: no-repeat;
									background-size: 1025px auto;
								}
			}
								@media (max-width: 479px) {
				#banner-map-225 .banner-map {
					height: 160px;
					background-position: 97% 3%;
					background-repeat: no-repeat;
									background-size: 533px auto;
								}
			}
		</style>
		
		<script type="text/javascript" src = "background_size_emu.js"></script>
	</head>
	
	<body>
		<div id="banner-map-225" class=" col-xxs-12 col-xs-12 col-sm-4 col-md-3 col-lg-3 tile">
			<div class="banner-map">
				<div class="visible-xxs"><div id="pl_66003587637" data-line-height="1.2" class=" text-label ui- ui--handle" style="left: 2.72109%; top: 10%; position: absolute;"><p style="line-height: 1.2;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231" style="line-height: 1.2;"><span style="color:#000000">Choose a chair<br>
									pick a paint<br>
									make it yours</span></a></p>
					</div><div id="pl_121734803257" data-line-height="1.05" class=" text-label ui- ui--handle" style="left: 2.38095%; top: 71px; padding: 0px; position: absolute;"><h3 style="line-height: 1.05;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231"><span style="color:#000000">SITTING</span><br>
								<span style="color:#cc0000">PRETTY<br>
									&gt;</span></a></h3>
					</div></div>
				<div class="visible-xs"><div id="pl_950425264430" data-line-height="1.05" class=" text-label ui- active ui--handle" style="left: 9.9833px; top: 66px; padding: 0px; position: absolute;"><h3 style="line-height: 1.05;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231"><span style="color:#000000">SITTING</span><br>
								<span style="color:#cc0000">PRETTY<br>
									&gt;</span></a></h3>
					</div><div id="pl_145247459719" data-line-height="1.2" class=" text-label ui- active ui--handle" style="left: 12px; top: 15.9833px; position: absolute;"><p style="line-height: 1.2;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231" style="line-height: 1.2;"><span style="color:#000000">Choose a chair<br>
									pick a paint<br>
									make it yours</span></a></p>
					</div></div>
				<div class="visible-sm"><div id="pl_158235766636" data-line-height="1.05" class=" text-label ui- ui--handle" style="left: 16px; top: 70px; padding: 0px; position: absolute;"><h3 style="line-height: 1.05;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231"><span style="color:#000000">SITTING</span><br>
								<span style="color:#cc0000">PRETTY<br>
									&gt;</span></a></h3>
					</div><div id="pl_948068105122" data-line-height="1.2" class=" text-label ui- ui--handle" style="left: 20px; top: 16.9833px; position: absolute;"><p style="line-height: 1.2;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231" style="line-height: 1.2;"><span style="color:#000000">Choose a chair<br>
									pick a paint<br>
									make it yours</span></a></p>
					</div></div>
				<div class="visible-md"><div id="pl_302801261358" data-line-height="1.15" class=" text-label ui- ui--handle" style="left: 14.6333px; top: 28.125%; padding: 0px; position: absolute;"><h3 style="line-height: 1.15;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231"><span style="color:#000000">SITTING</span><br>
								<span style="color:#cc0000">PRETTY<br>
									&gt;</span></a></h3>
					</div><div id="pl_246261148012" data-line-height="1.2" class=" text-label ui- ui--handle" style="left: 14.9667px; top: 8.33333%; position: absolute;"><p style="line-height: 1.2;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231" style="line-height: 1.2;"><span style="color:#000000">Choose a chair<br>
									pick a paint<br>
									make it yours</span></a></p>
					</div></div>
				<div class="visible-lg"><div id="pl_172358059015" data-line-height="1.1" class=" text-label ui- ui--handle" style="left: 5.37975%; top: 30.2083%; padding: 0px; position: absolute;"><h3 style="line-height: 1.1;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231"><span style="color:#000000">SITTING</span><br>
								<span style="color:#cc0000">PRETTY<br>
									&gt;</span></a></h3>
					</div><div id="pl_419915694895" data-line-height="1.2" class=" text-label ui- ui--handle" style="left: 6.32911%; top: 32px; position: absolute;"><p style="line-height: 1.2;"><a href="https://www.brewershome.co.uk/products/dining-chairs/brewers-home/bar-back-wooden-chair/124231" style="line-height: 1.2;"><span style="color:#000000">Choose a chair<br>
									pick a paint<br>
									make it yours</span></a></p>
					</div></div>
			</div>
		</div>
	</body>
</html>
[/code]

and what I see on the page is total mess
![test_bg_sz_emu](https://cloud.githubusercontent.com/assets/5286295/8872824/6e0e0bd8-3209-11e5-92d2-6c7b88037d35.png)

**Comment by Metafalica** [comment]
Would be much better if you provide me really an simple example.
Like single div with background-size set, so it's not working.

**Comment by Metafalica** [comment]
You can view here http://stackoverflow.com/questions/16350545/html-code-into-readme-md-on-github how to paste html code correctly in github

**Comment by Metafalica** [comment]
I tracked down the reason why it no working. Currently I don't know how to fix it, but that's the problem:
I always setting background-size, background-image, background-position right in element via `style = "blah; blah; blah;"` while you setting it in `style` tag.

So when it comes to check for elements with BG set the code for unknown reason don't see that div have background-image and background-size.

`var bg_sz = curr_elem.style.backgroundSize || curr_elem.style.getAttribute("background-size");`
the `bg_sz` for such elements is still undefined.

**Comment by michaelDotco2** [comment]
It will look like a mess because i didn't attach stylesheet or included images. I have updated now.

So it not working with the style tag will mean it will not work with media queries.
I dont think i can use it in my project. 

It isn't a simple example and I think your script will only work for simple cases.

**Comment by Metafalica** [comment]
That's right. Currently I trying to find a solution how to know if background set in `<style>` tag, but no success. Well, it's at least something.

**Comment by Metafalica** [comment]
What's the worst is that `background-size` not supported by ie6 - ie8, so those doesn't include this property even in `currentStyle`, so it probably impossible to know if this property set for element in `<style>`.

Other properties is possible to check even if those are set in `<style>`, but the `background-size` should be set inline.

**Comment by Metafalica** [comment]
This is most likely fixed by recent commits.
If no, then at least `background-size` must be set inline.
